name: Jekyll CI

'on':
  push:
    paths-ignore:
      - '*.md'
      - 'tests/feedcheck*.rb'
      - .github/workflows/feeds.yml
    branches:
      - master
  pull_request:
    paths-ignore:
      - '*.md'
      - 'tests/feedcheck*.rb'
      - .github/workflows/feeds.yml
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Ruby
        uses: ruby/setup-ruby@v1.172.0
        with:
          ruby-version: 3.2
          bundler-cache: true

      - name: Install Dependencies
        run: bundler install

      - name: Configure Feed Cache
        uses: actions/cache@v4
        with:
          path: planet.db
          key: cache-feed-sources-${{ hashFiles('Gemfile.lock') }}

      - name: Get and Proccess Feed Content
        run: bundler exec rake build

      - name: Build Jekyll Site
        run: bundler exec jekyll build
